#!/bin/bash

. "$HOME/.config/worm/down"
. "$HOME/.config/worm/utils"
. "$HOME/.cache/wal/colors.sh"

wallpaper="$(find "$HOME/Pictures/wallpapers" -type f | shuf -n 1)"
"$HOME"/.config/polybar/colorblocks/scripts/pywal.sh "$wallpaper" &

dunst \
  -frame_width 0 \
  -lb "${color0}" \
  -nb "${color0}" \
  -cb "${color0}" \
  -lf "${color7}" \
  -bf "${color7}" \
  -cf "${color7}" \
  -nf "${color7}" &
polkit-dumb-agent &
powerkit &
picom &
sxhkd -c ~/.config/sxhkd/sxhkdrc &
alttab &
"$HOME"/.config/polybar/launch.sh --colorblocks &
spicetify apply &

feh --bg-fill "$wallpaper"
wormc border-width 6
wormc focus-mode 1

pywal_active_index="3"   # color3
pywal_inactive_index="4" # color4
pywal_active="$(sed -n $(($pywal_active_index + 1))p ~/.cache/wal/colors | tail -c +2)"
pywal_inactive="$(sed -n $(($pywal_inactive_index + 1))p ~/.cache/wal/colors | tail -c +2)"

wormc border-active-pixel $((16#FF$pywal_active))
wormc border-inactive-pixel $((16#FF$pywal_inactive))
wormc frame-active-pixel $((16#FF$pywal_active))
wormc frame-inactive-pixel $((16#FF$pywal_inactive))
wormc text-active-pixel "$(contrast_text_for $pywal_active)"
wormc text-inactive-pixel "$(contrast_text_for $pywal_inactive)"

wormc layout floating
wormc struts 20 75 20 20 # up down left right
wormc gaps 20
wormc frame-height 0
