#!/bin/bash

contrast_text_for() {
  if perl -e "exit ((1 - (0.299 * $((16#${1:0:2})) + 0.587 * $((16#${1:2:2})) + 0.114 * $((16#${1:4:2}))) / 255) > 0.5)"; then
    echo $((16#FF000000))
  else
    echo $((16#FFFFFFFF))
  fi
}
